/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PumaTimer {
        "pause": () => Promise<void>;
        "restart": () => Promise<void>;
        "start": () => Promise<void>;
    }
}
declare global {
    interface HTMLPumaTimerElement extends Components.PumaTimer, HTMLStencilElement {
    }
    var HTMLPumaTimerElement: {
        prototype: HTMLPumaTimerElement;
        new (): HTMLPumaTimerElement;
    };
    interface HTMLElementTagNameMap {
        "puma-timer": HTMLPumaTimerElement;
    }
}
declare namespace LocalJSX {
    interface PumaTimer {
    }
    interface IntrinsicElements {
        "puma-timer": PumaTimer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "puma-timer": LocalJSX.PumaTimer & JSXBase.HTMLAttributes<HTMLPumaTimerElement>;
        }
    }
}
